[package]
name = "default-service"
version = "0.1.0"
authors = ["Weilbyte"]
edition = "2018"

[dependencies]
actix-web = "3"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.4.0"